sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t javilingt/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true javilingt/multi-docker-test npm run test

after_success:
  - docker build -t javilingt/multi-docker-client ./client
  - docker build -t javilingt/multi-docker-nginx ./nginx
  - docker build -t javilingt/multi-docker-worker ./worker
  - docker build -t javilingt/multi-docker-server ./server
  # log in docker cli
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push javilingt/multi-docker-client
  - docker push javilingt/multi-docker-nginx
  - docker push javilingt/multi-docker-server
  - docker push javilingt/multi-docker-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-119376223661"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY